apiVersion: argoproj.io/v1alpha1
kind: ArgoCD
metadata:
  name: user1-argocd
spec:
  rbac:
    defaultPolicy: ''
    policy: |
      g, system:cluster-admins, role:admin
    scopes: '[groups]'

