apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namePrefix: user1-

resources:
- ../../base
- namespace.yaml
- RB.yaml
- group.yaml

patchesStrategicMerge:
- argocd.yaml

