ReplicaNumber: 3

resources: 
  limits:
    cpu: 250m
    memory: 512Mi
  requests:
    cpu: 100m
    memory: 256Mi

containers:
  containerPort: 8080
  image: 'quay.io/argo-helm-workshop/hello-world:base'