apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: user1-argocd-instance
spec:
  destination:
    name: ''
    namespace: user1-argocd
    server: 'https://kubernetes.default.svc'
  source:
    path: Argocd-instances/
    repoURL: 'https://github.com/rhilconsultants/app-helm-argocd.git'
    targetRevision: main
  project: default
