kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: argocd-argocd-server
rules:
  - verbs:
      - get
      - patch
      - delete
    apiGroups:
      - '*'
    resources:
      - pods/exec
      - '*'
  - verbs:
      - create
      - get
      - list
      - watch
      - update
      - patch
      - delete
    apiGroups:
      - ''
    resources:
      - secrets
      - configmaps
  - verbs:
      - create
      - get
      - list
      - watch
      - update
      - delete
      - patch
    apiGroups:
      - argoproj.io
    resources:
      - applications
      - appprojects
  - verbs:
      - create
      - list
    apiGroups:
      - ''
    resources:
      - events
