kind: Route
apiVersion: route.openshift.io/v1
metadata:
  name: hello-world
spec:
  to:
    kind: Service
    name: {{ .Release.Name }}-service
    weight: 100
  port:
    targetPort: 8080
  wildcardPolicy: None

